project:
  type: website

execute:
  freeze: true

website:
  title: "Juan F. Tellez"
  search: false
  description: "Juan F. Tellez is an assistant professor at UC Davis."
  site-url: "https://juanftellez.com/"
  repo-url: "https://github.com/hail2thief/juan-quarto"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2019-2025 Juan Tellez</span>
      <span class="faux-block">All content licensed under[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>      
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/hail2thief/juan-quarto)</span>

format:
  html:
    theme: 
      - html/custom.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

bibliography: /Users/juan/Dropbox/github/whistle2/master.bib
csl: chicago-fullnote-bibliography.csl

